### ISSUE TITLE
Digilent_Vivado_Scripts submodule update failed due to non-existence of repo at given commit

### ISSUE THREAD

**Issue by shashwatssanghavi** [Digilent/Cora-Z7-10-Basic-IO#1]
Hi, I performed a clone from master. Submodule update failed, due to search failure of digilent_vivado_scripts failure at given commit.<br>

> git.exe submodule update --progress --init --recursive --merge -- "digilent-vivado-scripts"
fatal: remote error: upload-pack: not our ref ffa3f4f7bea46dc30645e1b618701ea3806b7707e-band side-band-64k ofs-delta shallow deepen-since deepen-not deepen-relative no-progress include-tag multi_ack_detailed allow-tip-sha1-in-want allow-reachable-sha1-in-want no-done symref=HEAD:refs/heads/master filter agent=git/github-g70eaaeb1276f
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'digilent-vivado-scripts', but it did not contain ffa3f4f7bea46dc30645e1b618701ea3806b7707. Direct fetching of that commit failed

**Comment by artvvb** [comment]
Fixed, thanks!
